[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel@^1.11.0
    adafruit/Adafruit PN532@^1.3.1
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/schreibfaul1/ESP32-audioI2S.git#v2.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_ENABLED=0
    -DCONFIG_WIFI_ENABLED=0
    -Isrc/utils
    -Isrc/activity_manager
    -Isrc/audio_player
    -Isrc/data_logger
    -Isrc/event_bus
    -Isrc/game
    -Isrc/hardware
    -Isrc/led_controller
    -Isrc/mood_registry
    -Isrc/nfc_handler
    -Isrc/session_manager
    -Isrc/time_service

build_src_filter =
    +<*>
    -<*/tests/>
    -<*/audio_player_wokwi.cpp>
    -<*/data_logger_wokwi.cpp>
    -<*/hardware_wokwi.cpp>
    -<*/nfc_handler_wokwi.cpp>
    -<*/activity_repository_wokwi.cpp>

monitor_speed = 115200

[env:esp32dev-release]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel@^1.11.0
    adafruit/Adafruit PN532@^1.3.1
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/schreibfaul1/ESP32-audioI2S.git#v2.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_ENABLED=0
    -DCONFIG_WIFI_ENABLED=0
    -Os
    -Isrc/utils
    -Isrc/activity_manager
    -Isrc/audio_player
    -Isrc/data_logger
    -Isrc/event_bus
    -Isrc/game
    -Isrc/hardware
    -Isrc/led_controller
    -Isrc/mood_registry
    -Isrc/nfc_handler
    -Isrc/session_manager
    -Isrc/time_service

build_src_filter =
    +<*>
    -<*/tests/>
    -<*/audio_player_wokwi.cpp>
    -<*/data_logger_wokwi.cpp>
    -<*/hardware_wokwi.cpp>
    -<*/nfc_handler_wokwi.cpp>
    -<*/activity_repository_wokwi.cpp>

monitor_speed = 115200

[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel@^1.11.0
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_ENABLED=0
    -DCONFIG_WIFI_ENABLED=0
    -DWOKWI_SIMULATION
    -Isrc/utils
    -Isrc/activity_manager
    -Isrc/audio_player
    -Isrc/data_logger
    -Isrc/event_bus
    -Isrc/game
    -Isrc/hardware
    -Isrc/led_controller
    -Isrc/mood_registry
    -Isrc/nfc_handler
    -Isrc/session_manager
    -Isrc/time_service

build_src_filter =
    +<*>
    -<*/tests/>
    -<nfc_handler/nfc_handler.cpp>
    -<audio_player/audio_player.cpp>
    -<data_logger/data_logger.cpp>
    -<hardware/hardware.cpp>
    -<*/activity_repository_sd.cpp>

monitor_speed = 115200

[env:native]
platform = native
build_flags =
    -DUNIT_TEST
    -std=c++11
    -Isrc/utils
    -Isrc/activity_manager
    -Isrc/audio_player
    -Isrc/data_logger
    -Isrc/event_bus
    -Isrc/game
    -Isrc/hardware
    -Isrc/led_controller
    -Isrc/mood_registry
    -Isrc/nfc_handler
    -Isrc/session_manager
    -Isrc/time_service
    -Itest/mocks

lib_deps =
    throwtheswitch/Unity@^2.6.0

build_src_filter =
    -<*>
    -<.git/>
    -<.svn/>

test_framework = unity
